name: README 实时更新

on:
  push:
    branches:
      - main
    paths:
      - 'v2ray/**'


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          cp node/README.md README.md
          TIME=$(date -u -d "+8 hours" '+%Y-%m-%dT%H:%M:%SZ')
          sed -i "s/<update_time>/$TIME/" README.md

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "$TIME 更新"
          git push origin
