name: clash节点

on:
  schedule:
    - cron: "0 */3 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 各种模块
        pip install --upgrade pip
        pip install requests
        pip install datetime


    - name: 删除旧生成的文件
      run: |
        rm -f clash/* || ture


    - name: 遍历运行py脚本并输出文本
      run: |
        for file in nodes/clash/*.py;do
        py_name=$(basename $file .txt)
        python "$file" > "clash/${py_name}.txt"
        done

        

    - name: 运行并输出结果clash
      run: |
        #python nodes/clash/naidounode.py > clash/1.txt
        #python nodes/clash/nodefree.py > clash/2.txt
        #python nodes/clash/nodev2ray.py > clash/3.txt
        #python nodes/clash/v2rayshare.py > clash/4.txt
        #python nodes/clash/wenode.py > clash/5.txt
        


    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "clash节点列表" && git push
        else
          echo "No changes to commit."
        fi
