name: v2ray节点

on:
  schedule:
    - cron: "0 */3 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 各种模块
        pip install --upgrade pip
        pip install requests
        pip install datetime


    - name: 删除旧生成的文件
      run: |
        rm -f v2ray/*.txt || ture
        rm -f v2ray.txt


    - name: 遍历运行py脚本并输出文本
      run: |
        for file in nodes/v2/*.py;do
        py_name=$(basename $file .py)
        python "$file" > "v2ray/${py_name}.txt"
        cat "v2ray/${py_name}.txt" >> v2ray.txt
        done


    - name: copy README.md
      run: |
        cp nodes/README.md README.md
        

    - name: README.md内容输出 clash
      run: |
        cd clash/
        list=""
        i=1
        for file in *.txt; do
          if [ -f "$file" ]; then
            list+="<td align=\"center\"><a href=\"https://cdn.jsdelivr.net/gh/xiaoji235/airport-free/clash/$file\">clash节点 $i</a></td>\n"
            ((i++))
          fi
        done
        list=$(echo "$list" | sed 's/$/\\n/g' | tr -d '\n') # Prepare list for insertion into README.md
        cd ..
        cp nodes/README.md README.md
        sed -i "/<clash_list>/c\\$list" README.md # Replace <v2ray_list> in README.md


    - name: README.md内容输出 v2ray
      run: |
        cd v2ray/
        list=""
        i=1
        for file in *.txt; do
          if [ -f "$file" ]; then
            list+="<td align=\"center\"><a href=\"https://cdn.jsdelivr.net/gh/xiaoji235/airport-free/v2ray/$file\">v2ray节点 $i</a></td>\n"
            ((i++))
          fi
        done
        list=$(echo "$list" | sed 's/$/\\n/g' | tr -d '\n')
        cd ..
        sed -i "/<v2ray_list>/c\\$list" README.md


    - name: README.md时间更新
      run: |
        TIME=$(date -u -d "+8 hours" '+%Y-%m-%d %H:%M:%S')
          sed -i "s/<update_time>/$TIME/" README.md

    - name: 去重
      run: |
        sort -u v2ray.txt > vpn.txt
        mv vpn.txt v2ray.txt
        rm -f v2ray/update.txt || ture

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "v2ray节点更新" && git push
        else
          echo "No changes to commit."
        fi
