name: v2ray节点

on:
  schedule:
    - cron: "0 */3 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 各种模块
        pip install --upgrade pip
        pip install requests
        pip install datetime


    - name: 删除旧生成的文件
      run: |
        rm -f v2ray/* || ture


    - name: 遍历运行py脚本并输出文本
      run: |
        for file in nodes/v2/*.py;do
        py_name=$(basename $file .py)
        python "$file" > "v2ray/${py_name}.txt"
        cat "v2ray/${py_name}.txt" >> v2ray.txt
        done


    #- name: 运行并输出结果v2
    #  run: |
        #python nodes/v2/naidounode.py > v2ray/1.txt
        #python nodes/v2/nodefree.py > v2ray/2.txt
        #python nodes/v2/nodev2ray.py > v2ray/3.txt
        #python nodes/v2/nodev2ray8.py > v2ray/4.txt
        #python nodes/v2/v2rayshare.py > v2ray/5.txt
        #python nodes/v2/wenode.py > v2ray/6.txt
        
        
    #- name: 合并结果vpn
    #  run: cat "v2ray/${py_name}.txt" > v2ray.txt

    - name: 去重
      run: |
        sort -u v2ray.txt > vpn.txt
        mv vpn.txt v2ray.txt
        rm -f v2ray/update.txt || ture

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "v2ray节点" && git push
        else
          echo "No changes to commit."
        fi
